# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application for project 3

on:
  push:
    paths:
      - 'project_3_deploy_model_with_fastapi/**'
      - '!project_2_short_term_rental_prices/**'
      - '!.github/workflows/**'
      - '!LICENSE'
      - '!README.md'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies of project 3
      run: |
        python -m pip install --upgrade pip
        if [ -f project_3_deploy_model_with_fastapi/requirements.txt ]; then pip install -r project_3_deploy_model_with_fastapi/requirements.txt; fi
    - name: Lint project 3 with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 project_3_deploy_model_with_fastapi/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 project_3_deploy_model_with_fastapi/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest in project 3
      run: |
        python -m pytest project_3_deploy_model_with_fastapi -vv
